'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const base = path.join(__dirname,'..');
const html = fs.readFileSync(path.join(base,'index.php'),'utf8');
let response = {ok:true,json:async()=>({ok:true,data:{status:'pending'}})};
const context = {window:{},document:{getElementById:()=>null},navigator:{},URLSearchParams,Intl,fetch:async()=>response};
vm.runInNewContext(fs.readFileSync(path.join(base,'assets/app.js'),'utf8'),context);
const {escape,money,api} = context.window.NatconUI;
(async()=>{
  assert.equal(escape('<img src=x onerror="bad">'), '&lt;img src=x onerror=&quot;bad&quot;&gt;');
  assert.equal(escape("O'Connor & co"), 'O&#39;Connor &amp; co');
  assert.equal(escape(null),'');
  assert.match(money(800000),/8,000/);
  assert.equal((await api('order',{},'GET')).status,'pending');
  response={ok:false,json:async()=>({ok:false,error:'Invalid token'})};
  await assert.rejects(api('ticket',{},'GET'),/Invalid token/);
  response={ok:false,json:async()=>{throw new Error('HTML response')}};
  await assert.rejects(api('event',{},'GET'),/unavailable/);
  const sw=fs.readFileSync(path.join(base,'sw.js'),'utf8');
  assert.match(sw,/ASSETS\.includes\(relative\) && !url\.search/);
  assert.doesNotMatch(sw,/cache\.put/);
  assert.doesNotMatch(fs.readFileSync(path.join(base,'assets/app.js'),'utf8'),/localStorage|sessionStorage|innerHTML\s*=\s*(?:error|result)\./);
  const app = fs.readFileSync(path.join(base,'assets/app.js'),'utf8');
  for (const field of ['email','course','institution','level','whatsapp','calling_line','state_origin','times_attended']) assert.match(app,new RegExp(`data-field="${field}"`),`delegate form collects ${field}`);
  assert.match(app,/NYSC</); assert.match(app,/Postgraduate</); assert.match(app,/Graduate</);
  assert.match(app,/api\('public_events',\{\},'GET'\)/,'published event selector reads the public NATCON catalogue');
  assert.match(app,/api\('event',\{event_id:eventId\},'GET'\)/,'selected event details use the canonical NATCON event endpoint');
  assert.match(app,/data\.event_id = String\(event\.event_id\)/,'web registration includes the selected event id');
  assert.match(app,/data\.ticket_type_id = selectedTicketTypeId/,'web registration includes the selected ticket type id');
  assert.equal(context.window.NatconUI.isDelegateIdFormatValid('TAA/NC/REFORMATION/001'),true);
  assert.equal(context.window.NatconUI.isDelegateIdFormatValid('TAA/NC/REFORMATION/01'),false);
  assert.equal(context.window.NatconUI.isDelegateIdFormatValid('TAA-NC-REFORMATION-001'),false);
  assert.match(app,/updateDelegateIdFeedback\(didInput\)/,'Delegate ID feedback updates while typing');
  assert.match(html,/id="privacy-consent" type="checkbox" required/,'privacy consent is an explicit required choice');
  assert.match(html,/role="progressbar"/,'registration progress is exposed accessibly');
  assert.match(html,/name="payment_method" value="transfer_new" data-bank-transfer/,'bank transfer is an explicit payment choice');
  assert.match(html,/name="payment_method" value="cash"/,'cash at venue is an explicit payment choice');
  assert.match(html,/accept="image\/jpeg,image\/png,image\/webp,application\/pdf"/,'receipts accept PDF and supported image formats');
  assert.doesNotMatch(html,/accommodation|accessibility/i,'removed needs are not requested on the registration page');
  assert.equal((html.match(/<footer\b/g)||[]).length,1,'conference page has one footer');
  assert.match(html,/href="privacy\.php" target="_blank" rel="noopener noreferrer"/,'privacy policy opens safely in a new tab');
  assert.doesNotMatch(html,/unpkg\.com\/aos/,'page motion does not depend on a third-party injection script');
  assert.match(fs.readFileSync(path.join(base,'..','services','natcon','bootstrap.php'),'utf8'),/finfo\(FILEINFO_MIME_TYPE\)/,'server checks uploaded receipt content');
  assert.match(fs.readFileSync(path.join(base,'..','.htaccess'),'utf8'),/conference\/privacy\/\?\$ conference\/privacy\.php/,'extensionless privacy route maps explicitly');
  assert.match(fs.readFileSync(path.join(base,'sw.js'),'utf8'),/natcon-static-v5/,'updated page assets invalidate the stale static cache');
  assert.match(fs.readFileSync(path.join(base,'..','api','natcon.php'),'utf8'),/action==='public_events'/,'API exposes published events without staff login');
  console.log('PASS: portal gates, including requested delegate fields, escaping, API failures, currency and private cache boundary');
})().catch(error=>{console.error(error);process.exitCode=1});
