<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';
use function Natcon\{config,migrate,register,confirmPayment,query,order,checkin,delegate,recover,createAccount,loginAccount,accountForToken,updateAccountProfile,staffForToken,issueMobileToken,mobileTicketHistory,mobileTicketInfo,mobileEventCard,mobileEventDetails,mobileTicketType,event};
$db=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);migrate($db);migrate($db);$c=config();$checks=0;
function delegateInput(string $name,string $email): array { return ['name'=>$name,'email'=>$email,'course'=>'Islamic Studies','institution'=>'Test University','level'=>'Graduate','whatsapp'=>'08000000000','calling_line'=>'','state_origin'=>'Osun','times_attended'=>'2']; }
function check($yes,string $label): void {global $checks;if(!$yes)throw new RuntimeException($label);$checks++;}
function rejects(callable $fn,string $label):void {try{$fn();}catch(InvalidArgumentException $e){check(true,$label);return;}throw new RuntimeException($label);}
$tables=array_column($db->query("SELECT name FROM sqlite_master WHERE type='table'")->fetchAll(),'name');
foreach(['natcon_accounts','natcon_mobile_tokens','natcon_categories','natcon_events','natcon_ticket_types','natcon_wallet_ledger','natcon_coupons','natcon_coupon_redemptions','natcon_favorites','natcon_reviews','natcon_referrals','natcon_payouts','natcon_event_media','natcon_artists','natcon_event_facilities','natcon_event_restrictions','natcon_faqs','natcon_pages','natcon_notifications','natcon_devices','natcon_chat_threads','natcon_chat_messages','natcon_otp_challenges'] as $table)check(in_array($table,$tables,true),'Mobile feature schema exists: '.$table);
$eventCard=mobileEventCard($c);check($eventCard['event_id']==='NATCON-2026'&&$eventCard['event_title']===$c['name'],'Mobile event discovery uses the canonical NATCON conference');
$eventDetails=mobileEventDetails($db,$c);check(isset($eventDetails['event_about'],$eventDetails['event_address'],$eventDetails['ticket_price'],$eventDetails['event_tags']),'Mobile event details satisfy the existing app model');
$mobileType=mobileTicketType($c);check((float)$mobileType['ticket_price']==(event($c)['price_kobo']/100)&&$mobileType['typeid']==='NATCON-GENERAL','Mobile ticket price is sourced from canonical server pricing');
// Attendee accounts use password hashes and revocable bearer tokens for mobile clients.
$account=createAccount($db,['name'=>'Account Test','email'=>'account@example.test','country_code'=>'+234','phone'=>'08001112222','password'=>'test-password-123']);
check(strlen($account['access_token'])===64,'Account registration issues a mobile token');
check(password_get_info(query($db,'SELECT password_hash FROM natcon_accounts WHERE id=?',[$account['id']])->fetchColumn())['algo']!==null,'Account password is hashed');
$loggedIn=loginAccount($db,['ccode'=>'+234','mobile'=>'08001112222','password'=>'test-password-123']);
check($loggedIn['id']===$account['id'],'Attendee phone and password login');
rejects(fn()=>loginAccount($db,['ccode'=>'+234','mobile'=>'08001112222','password'=>'incorrect-password']),'Wrong attendee password rejected');
$_SERVER['HTTP_AUTHORIZATION']='Bearer '.$loggedIn['access_token'];$authenticated=accountForToken($db);
check((int)$authenticated['id']===(int)$account['id'],'Attendee bearer token resolves account');
$updated=updateAccountProfile($db,(int)$account['id'],['name'=>'Updated Account','email'=>'updated@example.test']);
check($updated['name']==='Updated Account'&&$updated['email']==='updated@example.test','Attendee profile update');
$accountOrder=register($db,$c,['payer_name'=>'Updated Account','payer_email'=>'updated@example.test','payer_phone'=>'08001112222','consent'=>true,'delegates'=>[delegateInput('Account Delegate','account-delegate@example.test')] ],(int)$account['id']);
check((int)query($db,'SELECT account_id FROM natcon_orders WHERE reference=?',[$accountOrder['reference']])->fetchColumn()===(int)$account['id'],'Authenticated registrations are owned by the attendee account');
query($db,"UPDATE natcon_orders SET status='paid' WHERE reference=?",[$accountOrder['reference']]);$accountTickets=mobileTicketHistory($db,(int)$account['id'],$c);
check(count($accountTickets)===1&&$accountTickets[0]['event_title']===$c['name'],'Attendee history lists only paid tickets for the signed-in account');
$accountTicket=mobileTicketInfo($db,(int)$account['id'],$accountTickets[0]['ticket_id'],$c);
check($accountTicket['ticket_email']==='account-delegate@example.test'&&$accountTicket['qrcode']===$accountTicket['ticket_id'],'Attendee can retrieve their own canonical QR ticket');
rejects(fn()=>mobileTicketInfo($db,(int)$account['id']+999,$accountTickets[0]['ticket_id'],$c),'Another account cannot retrieve a paid attendee ticket');
query($db,'UPDATE natcon_mobile_tokens SET revoked_at=? WHERE token_hash=?',[Natcon\now(),hash('sha256',$loggedIn['access_token'])]);
check(accountForToken($db)===null,'Revoked mobile token denied');
unset($_SERVER['HTTP_AUTHORIZATION']);
query($db,'INSERT INTO natcon_staff(name,email,password_hash,role) VALUES(?,?,?,?)',['Staff Test','mobile-staff@example.test',password_hash('staff-test-password',PASSWORD_DEFAULT),'registrar']);
$staffId=(int)$db->lastInsertId();$staffToken=issueMobileToken($db,'staff',$staffId,'registrar');$_SERVER['HTTP_AUTHORIZATION']='Bearer '.$staffToken;
$mobileStaff=staffForToken($db);check((int)$mobileStaff['id']===$staffId&&$mobileStaff['role']==='registrar','Organizer bearer token resolves canonical staff identity and role');
query($db,'UPDATE natcon_mobile_tokens SET revoked_at=? WHERE token_hash=?',[Natcon\now(),hash('sha256',$staffToken)]);
check(staffForToken($db)===null,'Revoked staff mobile token denied');
unset($_SERVER['HTTP_AUTHORIZATION']);
$o=register($db,$c,['payer_name'=>'Test Payer','payer_email'=>'payer@example.test','payer_phone'=>'08000000000','amount_kobo'=>1,'consent'=>true,'delegates'=>[delegateInput('Delegate One','one@example.test'),delegateInput('Delegate Two','two@example.test')]]);
check((int)$o['amount_kobo']===1600000,'Server prices group registration');check(!isset($o['delegates'][0]['ticket_token']),'Unpaid tokens hidden');
$p=['status'=>'success','reference'=>$o['reference'],'amount'=>1600000,'currency'=>'NGN'];
rejects(fn()=>register($db,$c,['payer_name'=>'A','payer_email'=>'a@example.test','payer_phone'=>'08000000000','consent'=>true,'delegates'=>[['name'=>'Missing details','email'=>'a@example.test']]]),'Required delegate profile fields enforced');
rejects(fn()=>confirmPayment($db,$c,$o['reference'],array_replace($p,['amount'=>1])),'Reject wrong amount');
rejects(fn()=>confirmPayment($db,$c,$o['reference'],array_replace($p,['currency'=>'USD'])),'Reject currency');
rejects(fn()=>confirmPayment($db,$c,$o['reference'],array_replace($p,['reference'=>'other'])),'Reject reference');
check(confirmPayment($db,$c,$o['reference'],$p),'First confirmation changes status');check(!confirmPayment($db,$c,$o['reference'],$p),'Webhook replay idempotent');check((int)query($db,'SELECT COUNT(*) FROM natcon_outbox')->fetchColumn()===3,'Payer and each delegate receive one ticket email');
$saved=query($db,'SELECT email,course,institution,level,whatsapp,calling_line,state_origin,times_attended FROM natcon_delegates WHERE reference=? ORDER BY id LIMIT 1',[$o['reference']])->fetch();check($saved['email']==='one@example.test'&&$saved['course']==='Islamic Studies'&&$saved['institution']==='Test University'&&$saved['level']==='Graduate'&&$saved['whatsapp']==='08000000000'&&$saved['state_origin']==='Osun'&&(int)$saved['times_attended']===2,'Requested delegate profile persists');check(query($db,'SELECT phone FROM natcon_delegates WHERE reference=? ORDER BY id LIMIT 1',[$o['reference']])->fetchColumn()==='08000000000','Legacy phone field remains compatible');
$paid=order($db,$o['reference'],$o['access_token']);$token=$paid['delegates'][0]['ticket_token'];check(strlen($token)===64,'Opaque ticket');
check(checkin($db,$c,$token,'arrival',1,'2026-10-02')['result']==='accepted','Arrival on second day');check(checkin($db,$c,$token,'arrival',2,'2026-10-02')['result']==='already_checked_in','Duplicate denied across registrar');
check(checkin($db,$c,$token,'daily',1,'2026-10-03')['result']==='accepted','Daily attendance');check(checkin($db,$c,$token,'daily',2,'2026-10-03')['result']==='already_checked_in','Daily duplicate denied');
rejects(fn()=>checkin($db,$c,$token,'arrival',1,'2026-10-05'),'After conference rejected');rejects(fn()=>delegate($db,'bad'),'Invalid token rejected');
rejects(fn()=>order($db,$o['reference'],'wrong'),'Order secret required');
query($db,"UPDATE natcon_orders SET status='cancelled' WHERE reference=?",[$o['reference']]);rejects(fn()=>confirmPayment($db,$c,$o['reference'],$p),'Cancelled order cannot revive');
rejects(fn()=>register($db,$c,['payer_name'=>'A','payer_email'=>'bad','payer_phone'=>'x','consent'=>true,'delegates'=>[delegateInput('A','a@example.test')]]),'Bad email');
rejects(fn()=>register($db,$c,['payer_name'=>'A','payer_email'=>'good@example.test','payer_phone'=>'x','delegates'=>[delegateInput('A','a@example.test')]]),'Consent required');
// Finance can only reconcile the exact credit and never reuse a bank reference.
$transfer=register($db,$c,['payer_name'=>'Transfer Payer','payer_email'=>'transfer@example.test','payer_phone'=>'08000000004','consent'=>true,'delegates'=>[delegateInput('Transfer Delegate','transfer-delegate@example.test')]]);
query($db,"UPDATE natcon_orders SET status='awaiting_review',bank_reference='GATE-TRANSFER-001' WHERE reference=?",[$transfer['reference']]);
$transferPayment=['status'=>'success','reference'=>$transfer['reference'],'amount'=>(int)$transfer['amount_kobo'],'currency'=>'NGN'];
rejects(fn()=>confirmPayment($db,$c,$transfer['reference'],$transferPayment,'1',['amount_kobo'=>1]),'Reject wrong reconciled bank amount');
check(confirmPayment($db,$c,$transfer['reference'],$transferPayment,'1',['amount_kobo'=>(int)$transfer['amount_kobo']]),'Finance reconciliation confirms exact credit');
$again=register($db,$c,['payer_name'=>'Duplicate Bank','payer_email'=>'duplicate@example.test','payer_phone'=>'08000000005','consent'=>true,'delegates'=>[delegateInput('Duplicate Delegate','duplicate-delegate@example.test')]]);
query($db,"UPDATE natcon_orders SET status='awaiting_review',bank_reference='GATE-TRANSFER-001' WHERE reference=?",[$again['reference']]);
$againPayment=['status'=>'success','reference'=>$again['reference'],'amount'=>(int)$again['amount_kobo'],'currency'=>'NGN'];
rejects(fn()=>confirmPayment($db,$c,$again['reference'],$againPayment,'1',['amount_kobo'=>(int)$again['amount_kobo']]),'Reject reused bank transaction');
recover($db,$c,'transfer@example.test');
check((int)query($db,"SELECT COUNT(*) FROM natcon_outbox WHERE recipient='transfer@example.test'")->fetchColumn()>=2,'Paid ticket recovery is queued');
echo "PASS $checks backend gate assertions\n";
