<?php
declare(strict_types=1);
require dirname(__DIR__).'/bootstrap.php';require dirname(__DIR__).'/legacy-accounts.php';
use function Natcon\{migrate,query,createAccount,importLegacyAccounts,rollbackLegacyAccountImport,issueMobileToken};
$db=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);migrate($db);
$db->exec('CREATE TABLE tbl_user(id INTEGER PRIMARY KEY,name TEXT,email TEXT,ccode TEXT,mobile TEXT,password TEXT,refercode INTEGER,parentcode INTEGER,reg_date TEXT,status INTEGER,pro_pic TEXT,wallet INTEGER)');
query($db,'INSERT INTO tbl_user VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[1,'Legacy Alice','alice@example.test','+234','08000000001','alice-legacy-password',123456,null,'2025-01-02 03:04:05',1,'uploads/alice.jpg',18000]);
query($db,'INSERT INTO tbl_user VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[2,'Legacy Bob','bob@example.test','+234','08000000002','bob-legacy-password',123457,123456,'2025-01-03 03:04:05',1,'',0]);
query($db,'INSERT INTO tbl_user VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[3,'Invalid Legacy','not-an-email','+234','08000000003','long-enough-password',123458,null,'2025-01-04 03:04:05',1,'',50]);
createAccount($db,['name'=>'Existing NATCON','email'=>'conflict@example.test','country_code'=>'+234','phone'=>'08000000004','password'=>'existing-password-123']);
query($db,'INSERT INTO tbl_user VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[4,'Conflict Legacy','conflict@example.test','+234','08000000004','legacy-password-conflict',123459,null,'2025-01-05 03:04:05',1,'',100]);
$before=(int)query($db,'SELECT COUNT(*) FROM tbl_user')->fetchColumn();$batch='legacy-accounts-test-batch01';
$preview=importLegacyAccounts($db,$batch,false);if(!$preview['dry_run']||$preview['would_import']!==2||$preview['conflict_or_invalid']!==2||$preview['wallet_liability_kobo']!==1800000||(int)query($db,'SELECT COUNT(*) FROM natcon_legacy_account_imports')->fetchColumn()!==0)throw new RuntimeException('Dry run must report scope and liability without writing imported records.');
$applied=importLegacyAccounts($db,$batch,true);if($applied['imported']!==2||$applied['skipped']!==2||$applied['dry_run'])throw new RuntimeException('Apply imports only eligible legacy accounts.');
$alice=query($db,'SELECT * FROM natcon_accounts WHERE email=?',['alice@example.test'])->fetch();$bob=query($db,'SELECT * FROM natcon_accounts WHERE email=?',['bob@example.test'])->fetch();
if(!password_verify('alice-legacy-password',$alice['password_hash'])||$alice['profile_image']!=='uploads/alice.jpg'||(int)$alice['wallet_balance_kobo']!==1800000||(int)$bob['referred_by']!==(int)$alice['id']||(int)query($db,'SELECT COUNT(*) FROM natcon_referrals WHERE referred_account_id=? AND reward_kobo=0',[$bob['id']])->fetchColumn()!==1)throw new RuntimeException('Import hashes passwords and preserves image, wallet liability, and reward-free referral attribution.');
if((int)query($db,'SELECT COUNT(*) FROM tbl_user')->fetchColumn()!==$before||query($db,'SELECT password FROM tbl_user WHERE id=1')->fetchColumn()!=='alice-legacy-password')throw new RuntimeException('Import must leave legacy source rows unchanged.');
$again=importLegacyAccounts($db,$batch,true);if($again['imported']!==0||$again['already_imported']!==2)throw new RuntimeException('Repeat import must be idempotent.');
query($db,'UPDATE natcon_accounts SET name=? WHERE id=?',['Changed after import',(int)$alice['id']]);try{rollbackLegacyAccountImport($db,$batch);throw new RuntimeException('Rollback must refuse modified imported accounts.');}catch(RuntimeException $e){if(!str_contains($e->getMessage(),'changed since migration'))throw $e;}query($db,'UPDATE natcon_accounts SET name=? WHERE id=?',['Legacy Alice',(int)$alice['id']]);
issueMobileToken($db,'attendee',(int)$alice['id']);try{rollbackLegacyAccountImport($db,$batch);throw new RuntimeException('Rollback must refuse accounts already used in NATCON.');}catch(RuntimeException $e){if(!str_contains($e->getMessage(),'Rollback refused'))throw $e;}
query($db,'DELETE FROM natcon_mobile_tokens WHERE principal_type=? AND principal_id IN (?,?)',['attendee',(int)$alice['id'],(int)$bob['id']]);$rolled=rollbackLegacyAccountImport($db,$batch);if($rolled['rolled_back']!==2||(int)query($db,'SELECT COUNT(*) FROM natcon_accounts WHERE email IN (?,?)',['alice@example.test','bob@example.test'])->fetchColumn()!==0||(int)query($db,'SELECT COUNT(*) FROM tbl_user')->fetchColumn()!==$before)throw new RuntimeException('Safe rollback removes only untouched imported NATCON records and preserves legacy source data.');
echo "PASS reversible legacy account migration: dry-run, conflicts, password hashing, wallet/referral preservation, idempotency, safe rollback\n";
